version: 2
updates:
  - package-ecosystem: "npm" # Bun is not available.
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps"
    auto-merge: true